package kg.itschool.demo.model.entity;

public enum Authority {

    USER_READ,
    USER_CREATE,
    USER_DELETE,
    USER_UPDATE,

    ACCOUNT_READ,
    ACCOUNT_CREATE,
    ACCOUNT_DELETE,
    ACCOUNT_UPDATE,

    TRANSACTION_READ,
    TRANSACTION_CREATE,
    TRANSACTION_DELETE,

    ROLE_CREATE,
    PERMISSIONS_READ,

    GUEST_READ
}
